language: python
python:
  - 2.6
  - 2.7
  - pypy
install:
  - if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pip install unittest2 --use-mirrors; fi
  - pip install -r tests/requirements.txt
  - pip install .
script: nosetests -q tests
